// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace my_app.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200830120510_departamenti_table")]
    partial class departamenti_table
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAL.Models.Departamenti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emaili")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Emri")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SindikataId")
                        .HasColumnType("int");

                    b.Property<string>("Telefoni")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Themelimi")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("SindikataId");

                    b.ToTable("Departamenti");
                });

            modelBuilder.Entity("DAL.Models.Sindikata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresa")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Emaili")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Emri")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Themelimi")
                        .HasColumnType("datetime");

                    b.Property<string>("Zip")
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Sindikatas");
                });

            modelBuilder.Entity("DAL.Models.Departamenti", b =>
                {
                    b.HasOne("DAL.Models.Sindikata", "Sindikata")
                        .WithMany("Departamentis")
                        .HasForeignKey("SindikataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
